version: '3.8'

services:
  app:
    image: ruby:3.1.2
    command: sh -c "bundle && bundle exec yard server --one-file --output-dir .yardoc --reload -B 0.0.0.0 -p 8808"
    healthcheck:
      test: ["CMD-SHELL", "bundle exec yard --one-file --output-dir .yardoc || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 50
    dns:
      - 8.8.8.8
    ports:
      - "8808:8808"
    tty: true
    stdin_open: true
    user: "1000:1000"
    working_dir: $PWD
    volumes:
      - type: bind
        source: "."
        target: "$PWD"
      - type: bind
        source: "/tmp"
        target: "/tmp"
    environment:
      - GEM_HOME=${PWD}/vendor/bundle
      - BUNDLE_JOBS=4
      - BUNDLE_RETRY=3
      - BUNDLE_DEPLOYMENT=false
      - BUNDLE_PATH=${PWD}/vendor/bundle
      - BUNDLE_APP_CONFIG=${PWD}/vendor/bundle
      - BUNDLE_BIN=${PWD}/vendor/bundle/bin
      - HOME=${PWD}/tmp/home
      - TZ=Asia/Tokyo

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1258}
